-- Create profiles table if it doesn't exist
create table if not exists public.profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  email text,
  phone text,
  city text,
  state text,
  country text,
  linkedin_url text,
  github_url text,
  portfolio_url text,
  current_company text,
  current_title text,
  resume_path text,
  race text,
  veteran_status text,
  disability_status text,
  primary_role text
);

-- Add columns if they don't exist (for existing tables)
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'race') then
    alter table public.profiles add column race text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'veteran_status') then
    alter table public.profiles add column veteran_status text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'disability_status') then
    alter table public.profiles add column disability_status text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'profiles' and column_name = 'primary_role') then
    alter table public.profiles add column primary_role text;
  end if;
end $$;

-- Create experiences table
create table if not exists public.autofill_experiences (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  company_name text,
  job_title text,
  location text,
  start_month text,
  start_year integer,
  end_month text,
  end_year integer,
  is_current boolean,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create educations table
create table if not exists public.autofill_educations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  school_name text,
  degree_type text,
  major text,
  start_month text,
  start_year integer,
  end_month text,
  end_year integer,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create skills table
create table if not exists public.autofill_skills (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  skill_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create languages table
create table if not exists public.autofill_languages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  language_name text,
  proficiency text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.autofill_experiences enable row level security;
alter table public.autofill_educations enable row level security;
alter table public.autofill_skills enable row level security;
alter table public.autofill_languages enable row level security;

-- Create policies
-- Profiles
drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles for insert with check (auth.uid() = id);

-- Experiences
drop policy if exists "Users can view own experiences" on public.autofill_experiences;
create policy "Users can view own experiences" on public.autofill_experiences for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own experiences" on public.autofill_experiences;
create policy "Users can insert own experiences" on public.autofill_experiences for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update own experiences" on public.autofill_experiences;
create policy "Users can update own experiences" on public.autofill_experiences for update using (auth.uid() = user_id);

drop policy if exists "Users can delete own experiences" on public.autofill_experiences;
create policy "Users can delete own experiences" on public.autofill_experiences for delete using (auth.uid() = user_id);

-- Educations
drop policy if exists "Users can view own educations" on public.autofill_educations;
create policy "Users can view own educations" on public.autofill_educations for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own educations" on public.autofill_educations;
create policy "Users can insert own educations" on public.autofill_educations for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update own educations" on public.autofill_educations;
create policy "Users can update own educations" on public.autofill_educations for update using (auth.uid() = user_id);

drop policy if exists "Users can delete own educations" on public.autofill_educations;
create policy "Users can delete own educations" on public.autofill_educations for delete using (auth.uid() = user_id);

-- Skills
drop policy if exists "Users can view own skills" on public.autofill_skills;
create policy "Users can view own skills" on public.autofill_skills for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own skills" on public.autofill_skills;
create policy "Users can insert own skills" on public.autofill_skills for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update own skills" on public.autofill_skills;
create policy "Users can update own skills" on public.autofill_skills for update using (auth.uid() = user_id);

drop policy if exists "Users can delete own skills" on public.autofill_skills;
create policy "Users can delete own skills" on public.autofill_skills for delete using (auth.uid() = user_id);

-- Languages
drop policy if exists "Users can view own languages" on public.autofill_languages;
create policy "Users can view own languages" on public.autofill_languages for select using (auth.uid() = user_id);

drop policy if exists "Users can insert own languages" on public.autofill_languages;
create policy "Users can insert own languages" on public.autofill_languages for insert with check (auth.uid() = user_id);

drop policy if exists "Users can update own languages" on public.autofill_languages;
create policy "Users can update own languages" on public.autofill_languages for update using (auth.uid() = user_id);

drop policy if exists "Users can delete own languages" on public.autofill_languages;
create policy "Users can delete own languages" on public.autofill_languages for delete using (auth.uid() = user_id);

-- Storage Policies (for 'resumes' bucket)
-- Allow authenticated users to upload files to the 'resumes' bucket
drop policy if exists "Users can upload own resume" on storage.objects;
create policy "Users can upload own resume" on storage.objects for insert with check (
  bucket_id = 'resumes' and
  auth.role() = 'authenticated' and
  (storage.foldername(name))[1] = auth.uid()::text
);

-- Allow authenticated users to view their own resume
drop policy if exists "Users can view own resume" on storage.objects;
create policy "Users can view own resume" on storage.objects for select using (
  bucket_id = 'resumes' and
  auth.role() = 'authenticated' and
  (storage.foldername(name))[1] = auth.uid()::text
);

-- Allow authenticated users to update their own resume
drop policy if exists "Users can update own resume" on storage.objects;
create policy "Users can update own resume" on storage.objects for update using (
  bucket_id = 'resumes' and
  auth.role() = 'authenticated' and
  (storage.foldername(name))[1] = auth.uid()::text
);

-- Allow authenticated users to delete their own resume
drop policy if exists "Users can delete own resume" on storage.objects;
create policy "Users can delete own resume" on storage.objects for delete using (
  bucket_id = 'resumes' and
  auth.role() = 'authenticated' and
  (storage.foldername(name))[1] = auth.uid()::text
);
